mainConfiguration: https://github.com/elixir-europe-training/ELIXIR-TrP-Training-Metrics-Database-Tango

tasks:
  - name: Setup and startup
    init: |
      cp -n .env.default .env
      cp -n postgres/postgres.env.default postgres/postgres.env
    command: docker compose up -d
  - name: Populate database
    init: |
      gp ports await 8000
      docker compose exec tango python manage.py load_data

ports:
  - name: Django
    description: the port used by the Django container
    port: 8000
    onOpen: open-preview
    visibility: public
  - name: Postgres
    description: the port used by the Postgres container
    port: 5432
    onOpen: ignore