---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-executables-have-shebangs
      # - id: check-json
      # - id: pretty-format-json
      - id: check-symlinks
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    # Formats, sorts and reorganizes imports
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - "--filter-files"
          - "--thirdparty"
          - "mmpy_bot"
  - repo: https://github.com/psf/black
    # Code style formatting
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    # static type analysis
    rev: v1.3.0
    hooks:
      - id: mypy
        # This is something we want to enable but currently there are too many
        # errors from thirdparty libs
        additional_dependencies:
          - django
          - typing-extensions
  - repo: https://github.com/PyCQA/flake8
    # Checks the code for PEP8 violations and common pitfals
    rev: 3.9.0
    hooks:
      - id: flake8
        args:
          - "--config"
          - "setup.cfg"
  - repo: https://github.com/myint/docformatter
    # Formats docstrings following PEP 257
    rev: v1.3.1
    hooks:
      - id: docformatter
        args:
          - "--in-place"
  - repo: https://github.com/asottile/pyupgrade
    # updates syntax to use constructs introduced in newer python versions
    # e.g. f-strings instead of "{}".format()
    rev: v2.13.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
  - repo: https://github.com/pycqa/doc8
    # sphinx rst style checker
    rev: v1.1.1
    hooks:
      - id: doc8
