version: "3"
services:
  tango:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/
    restart: on-failure
    env_file: .env
    ports:
      - 127.0.0.1:8000:8000
